# Source the colors from wallbash
# See the file first to see the equivalent colors
source = hyprlock/colors.conf

# Script Path
$music = hyprlock/scripts/playerctlock.sh
$album = hyprlock/scripts/hlock_mpris.sh
$battery = hyprlock/scripts/battery.sh
$location = hyprlock/scripts/location.sh
$weather = hyprlock/scripts/weather.sh

# source = hyprlock/layouts/layout1.conf
# source = hyprlock/layouts/layout5.conf
# source = hyprlock/layouts/layout6.conf
# source = hyprlock/layouts/layout8.conf
# source = hyprlock/layouts/layout9.conf
# source = hyprlock/layouts/layout10.conf
# source = hyprlock/layouts/layout11.conf
# source = hyprlock/layouts/layout13.conf
 source = hyprlock/layout17.conf


auth {
    pam:enabled = true
    fingerprint:enabled = true
}